### ISSUE TITLE
add translator extension metadata to openapi spec

### ISSUE THREAD

**Issue by balhoff** [NCATS-Tangerine/cam-kp-api#168]
We need to insert this structure into the "info" object in our YAML spec:

```yaml
x-translator:
  component": "KP"
  team:
    - "Exposures Provider"
```

This doesn't seem to be supported by the Tapir API. We may need to try using Circe to parse the YAML string it generates, tweak the JSON object, and then reserialize to a YAML string.
