### ISSUE TITLE
team value in metadata should be a list

### ISSUE THREAD

**Issue by balhoff** [NCATS-Tangerine/cam-kp-api#195]
@jdr0887 pointed out that it should be like this:

```
 x-translator:
    component: KP
    team:
      - Exposures Provider
```
